### ISSUE TITLE
Cannot update metadata schema anymore

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#1]
When trying to set Topic Classification as hidden in the metadata schema of the TGO sub-collection (and other sub-collections), I get the following error message:

This dataverse was not able to be updated. – Please contact DataverseNO for assistance. Date/Time: 2021-10-25 11:58:41 Server: test.dataverse.no

**Comment by philippconzett** [comment]
@philippconzett Once this issue is fixed, hide Top Classification in all sub-collections.

**Comment by philippconzett** [comment]
@oodu Have you had a look at this issue? I reproduced the error this morning,

between 2021-11-10T06:09:00.000+0200 and 2021-11-10T06:011:00.000+0200

**Comment by oodu** [comment]
Can you point me to the dataset/dataverse that produced the error?

Obi

**Comment by philippconzett** [comment]
It's all sub-collections. For example: [https://dataverse.no/dataverse/gnss](https://dataverse.no/dataverse/gnss). You can try to set "Top Classification" as hidden. Please do not change other settings.

**Comment by philippconzett** [comment]
This issue will probably be solved once we upgrade to v. 5.9; see Phil Durbin's answer in the Dataverse Google Group:
[https://groups.google.com/u/1/g/dataverse-community/c/DUvzLTjvPTs](https://groups.google.com/u/1/g/dataverse-community/c/DUvzLTjvPTs).

**Comment by Louis-wr** [comment]
Fixed by upgrading to 5.9.
Test done

**Comment by philippconzett** [comment]
Was able to remove Topic Classifiacation and save updated metadata schema in all sub-collections at stake.
