### ISSUE TITLE
Dataset with Handle as primary PID

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#18]
**Describe the bug**
There is one dataset in DataverseNO/TROLLing that still has a Handle as it primary PID:
[https://dataverse.no/dataset.xhtml?persistentId=hdl:10037.1/10196&version=1.0](https://dataverse.no/dataset.xhtml?persistentId=hdl:10037.1/10196&version=1.0)

**To Reproduce**
1. Go to [https://dataverse.no/dataset.xhtml?persistentId=hdl:10037.1/10196&version=1.0](https://dataverse.no/dataset.xhtml?persistentId=hdl:10037.1/10196&version=1.0)
2. See the dataset reference, which contains a Handle instead of a DOI.
3. Click on the Metadata tab, where you'll see the Handle displayed as Dataset Persistent ID:

![image](https://user-images.githubusercontent.com/21955790/177790836-5e73581c-af1f-441c-b1b2-93db91d732a1.png)

**Expected behavior**
The dataset should have a DOI as its primary PID, and Handle as its secondary PID. See another TROLLing dataset with correct PID  setup: [https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/TJUSQA](https://dataverse.no/dataset.xhtml?persistentId=doi:10.18710/TJUSQA)

![image](https://user-images.githubusercontent.com/21955790/177791454-5f6b073e-acec-4c67-a437-3c81033815f6.png)

**Screenshots**
See above.

**Additional context**
The dataset has a draft version which was created in 2015. We have contacted the author and asked whether this draft can be deleted.

Back in 2016 when TROLLing switched from Handle to DOI, Harvard/the Dataverse community provided a script to add DOI as primary PIDs to all datasets and move the Handle to field Previous Dataset Persistent ID. It seems that this dataset for some reason wasn't converted properly at that time.

**Comment by philippconzett** [comment]
@oodu Please add the command you run to solve this issue.

**Comment by oodu** [comment]
From the url: https://guides.dataverse.org/en/5.3/admin/dataverses-datasets.html:
Mints a new identifier for a dataset previously registered with a handle. Only accessible to superusers.

Search for any dataset that has handle (hdl) as it primary persistent id in the database: SELECT * FROM dvobject where protocol like '%hdl%';  -> id = 27
Get the token from the superuser, dataverseAdmin: f0372bad-aa8c-4ee3-8c00-d41xxxxxxxxxxx
Run the curl command as root:  curl -H "X-Dataverse-key: $API_TOKEN" -X POST http://$SERVER/api/admin/$dataset-id/reregisterHDLToPID
curl -H "X-Dataverse-key: f0372bad-aa8c-4ee3-8c00-d41xxxxxxxxxxx" -X POST http://localhost:8080/api/admin/27/reregisterHDLToPID
