### ISSUE TITLE
Change wording in General Terms of Use, displayed at user account sign up

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#19]
The wording in the General Terms of Use, displayed at user account sign up should be changed as follows:

From
`The General Terms of Use for DataverseNO, including all its sub-repositories, are described in the [DataverseNO Policy Framework](https://site.uit.no/dataverseno/about/policy-framework/)`
to
`The General Terms of Use for DataverseNO are described in the [DataverseNO Policy Framework](https://site.uit.no/dataverseno/about/policy-framework/)`
thus remove
`, including all its sub-repositories,`

See screenshot:
![image](https://user-images.githubusercontent.com/21955790/187618931-89c4a9c7-5ee3-4aab-bca5-096872cae8b8.png)

**Comment by oodu** [comment]
The wording in the General Terms of Use, displayed at user account sign up should be changed as follows:
