### ISSUE TITLE
Thumbnails (of some file types) not displaying correctly on dataverse.no

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#2]
**Describe the bug**
The thumbnails (of some file types) are not displaying correctly on dataverse.no.

**To Reproduce**
1. Go to [https://doi.org/10.18710/AWRGH1](https://doi.org/10.18710/AWRGH1).
2. Select the File tab (if not selected by default).
3. Have a look at the thumbnails of the .tiff files.

**Expected behavior**
Thumbnails should display as images.

**Screenshots**
![image](https://user-images.githubusercontent.com/21955790/137582651-b212c6c8-4a2b-4b5f-b6bc-764cbad93e50.png)

**Desktop (please complete the following information):**
 - Device: Lenovo
 - OS: Windows 10
 - Browser: Tested on Chrome, Edge, and Firefox, with the same result; see screenshot.

**Comment by philippconzett** [comment]
One of our partners has just informed us that this issue also affects their collection; see page 2 in the INN collection:
[https://dataverse.no/dataverse/inn?q=&types=dataverses%3Adatasets&sort=dateSort&order=desc&page=2](https://dataverse.no/dataverse/inn?q=&types=dataverses%3Adatasets&sort=dateSort&order=desc&page=2)

![image](https://user-images.githubusercontent.com/21955790/149754777-8a894125-c65b-4678-b533-1ee6b174491f.png)


Obi: can you fix this? Thanks!

**Comment by Louis-wr** [comment]
we are getting a 0bits files from .tiff 
A possible linked issue :
https://groups.google.com/g/dataverse-community/c/K9eUCw8erKc

**Comment by Louis-wr** [comment]
> One of our partners has just informed us that this issue also affects their collection; see page 2 in the INN collection: https://dataverse.no/dataverse/inn?q=&types=dataverses%3Adatasets&sort=dateSort&order=desc&page=2
> 
> ![image](https://user-images.githubusercontent.com/21955790/149754777-8a894125-c65b-4678-b533-1ee6b174491f.png)
> 
> Obi: can you fix this? Thanks!

Obi did you fix the INN collection already?
![image](https://user-images.githubusercontent.com/85620187/149895953-ff3f64d7-5adc-4338-9201-50281bafe528.png)

**Comment by philippconzett** [comment]
Is this also related to the error messages that are continuously filling up our log files?

**Comment by Louis-wr** [comment]
> Is this also related to the error messages that are continuously filling up our log files?

this type of entry:
[2022-01-13T11:57:53.071+0100] [Payara 5.2021.6] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid: _ThreadID=109 _ThreadName=http-thread-pool::jk-connector(5)] [timeMillis: 1642071473071] [levelValue: 900] [[
  Caught exception attempting to read the image file with ImageIO.read(InputStream)]]
  
  It indeed very well could be

**Comment by philippconzett** [comment]
Obi will write a script that puts a placeholder thumbnail for all files that don't have a thumbnail, e.g. some .tif files.

**Comment by philippconzett** [comment]
@oodu @Louis-wr @4tikhonov Could you have another go at this issue? The partner institution has just sent a reminder about this. Maybe can do this as easy as just turning off thumbnails for all TIFF-files (.tif, .tiff). Thanks!

**Comment by philippconzett** [comment]
I raised this issue in the Dataverse Google group:
[https://groups.google.com/u/1/g/dataverse-community/c/x_g9mE5V1UI](https://groups.google.com/u/1/g/dataverse-community/c/x_g9mE5V1UI)

When I try to edit the dataset thumbnail (see one of the suggestions in the Dataverse Google group thread above), I cannot access the configuration page, but get this error message:

![image](https://user-images.githubusercontent.com/21955790/175519541-bda6e3ce-4d78-4353-8fab-c821422442a3.png)

So, it seems the imageMagic is still trying to create the thumbnail?
Maybe limiting the size of thumbnails somewhat more would help? Cf. [https://guides.dataverse.org/en/latest/installation/config.html?highlight=thumbnail#dataverse-dataaccess-thumbnail-image-limit](https://guides.dataverse.org/en/latest/installation/config.html?highlight=thumbnail#dataverse-dataaccess-thumbnail-image-limit).

**Comment by philippconzett** [comment]
Any progress on this issue? @oodu?

**Comment by oodu** [comment]
Done

**Comment by oodu** [comment]
./10.18710/QEOFPY/169a515adee-a3dbc102089c.thumb[48, 64, 140, 400],   ok
./10.18710/DUANRP/16fc1c8a50a-5afd52d18524.thumb[48, 64, 140, 400]  ok
./10.18710/TYPJXU/173dd19d406-9872ffacedec.thumb[48, 64, 140, 400]  ok
./10.18710/IMPEG8/17821f5e780-5ff43ba39cf2.thumb[48, 64, 140, 400]  ok
./10.18710/AWRGH1/17c3b19942d-11ce409b2d08.thumb[48, 64, 140, 400] ok

**Comment by oodu** [comment]
I will change the configuration to limit the size of thumbnail generated to see if it will work at test dataverse.
