### ISSUE TITLE
Delete dataset 10.5072/FK2/VA3BVU

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#20]
Something must have gone wrong when we created and "published" dataset 10.5072/FK2/VA3BVU ([https://dataverse.no/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FVA3BVU](https://dataverse.no/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FVA3BVU)), because the dataset got assigned a test DOI, 10.5072/FK2/VA3BVU, and thus is not findable. We have been discussing this issue for a long time and concluded that we need to recreate the dataset, and then delete the one with the test DOI. We've got approval for this from the authors. The new dataset which is replacing the one with the test DOI is the following one: [https://dataverse.no/dataset.xhtml?persistentId=doi%3A10.18710%2FYKZBMR](https://dataverse.no/dataset.xhtml?persistentId=doi%3A10.18710%2FYKZBMR). It's not published yet.

**Comment by oodu** [comment]
I think what should be done here is to perform api "Deaccession Dataset" on the dataset 10.5072/FK2/VA3BVU. 

curl -H 'X-Dataverse-key: 2395xxxxxxxtokengenereated' -X DELETE https://dataverse.no/api/datasets/:persistentId/destroy?persistentId=doi:10.5072/FK2/VA3BVU . 
If any error messages during the execution, we could delete Key (id)=(xxx) associated with dataset from the database and perform again api  

delete from datafilecategory where dataset_id=xxx;

We can test this at test-docker.dataverse.no or at test.dataverse.no

**Comment by philippconzett** [comment]
No, this is not a matter of deaccessioning, but deleting. The dataset got a wrong DOI, for reasons no-one so far has been able to explain. I have contacted the authors and we decided to recreate the dataset and then delete the old one. I have recreated the dataset, so now, the old one should be permanently deleted. @4tikhonov @Louis-wr @oodu

**Comment by philippconzett** [comment]
The replacing dataset has been successfully published. Obi: please delete permanently dataset 10.5072/FK2/VA3BVU.

**Comment by oodu** [comment]
The dataset 10.5072/FK2/VA3BVU is permanently deleted from dataverse.no.

Obi

**Comment by philippconzett** [comment]
Thanks!
