### ISSUE TITLE
Account information clean-up

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#24]
When we launched TROLLing, we didn't have a Feide integration. Before a workshop we ran, we create user accounts with local authentication for the participants. As user name and email address we chose the participants' Feide user name and their UiT email address. Those old user account now cause trouble when these UiT employees try to log in with Feide, because there already exist user accounts with the values Feide provides (Feide user name and UiT email address).

To solve this problem, we can add "xxx" or similar to the fields id and email in the database table authenticateduser of these old user accounts. I have created a bash script we can run to do this. Here is an anonymized example line:

update authenticateduser set id='abc000xxx', email='abc.defgxxx@uit.no' where id=41;

The bash file (dvno_user_account_cleaning_2022.sh) is available in Teams >> General >> Feide.

Please try it out in one of our test environment, and if successful, in the production environment. Thanks!

**Comment by Louis-wr** [comment]
added functionality
https://github.com/DataverseNO/dataverse-docker/blob/dataverse.no/distros/dataverse.no/init.d/0001-cleanup.sh
