### ISSUE TITLE
Cannot log into test.dataverse.no anymore

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#25]
**Describe the bug**
I get the error message below when I try to log into test.dataverse.no with test Feide.

Unhandled exception
An unhandled exception was thrown.

If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

Tracking number:
94d5181251

**Comment by philippconzett** [comment]
I tried once more in incognito mode. This time I got this error message:

Unhandled exception
An unhandled exception was thrown.

If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

Tracking number:
8946babd58

**Comment by Louis-wr** [comment]
Looks like something is wrong with idp-test.feide.no it tried on on both test.dataverse.no and test-docker.dataverse.no.
If this error persist tomorrow it will be time to contact feide.

**Comment by philippconzett** [comment]
Thanks. Let's check again tomorrow.

**Comment by philippconzett** [comment]
The error still persists on both test.dataverse.no and test-docker.dataverse.no.
@Louis-wr could you contact Uninett about this? Thanks!

**Comment by philippconzett** [comment]
The error was caused by an update at Uninett and has been resolved now.
