### ISSUE TITLE
File number indication not working properly

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#30]
When logged in as a curator or admin in dataverse.no and test.dataverse.no, I can see the number of files indicated in the facet section to the left. However, when I narrow down the selection to include only published datasets by clicking the Published (xxxx) link in the Publication Status section, no file numbers are indicated anymore.

Julian from IQSS confirmed that this probably is an error in our setup; see [discussion thread](https://groups.google.com/u/2/g/dataverse-community/c/sFqbXENasBo) in Dataverse Google Group.

**Comment by Louis-wr** [comment]
Could you elaborate a bit more? we took a look and we cant seam to reproduce the issue.
If you can could you post a screenshot?
