### ISSUE TITLE
Add Data Privacy Statement to dataverse.no

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#33]
A link to the DataverseNO Privacy Statement should be added to dataverse.no. See how to in the Dataverse guide: [https://guides.dataverse.org/en/latest/installation/config.html?highlight=footer#applicationprivacypolicyurl](https://guides.dataverse.org/en/latest/installation/config.html?highlight=footer#applicationprivacypolicyurl).

In the command, replace

https://dataverse.org/best-practices/harvard-dataverse-privacy-policy

with

https://site.uit.no/dataverseno/about/policy-framework/access-and-use-policy/

This should also be reflected in the new cloud-based instance of DataverseNO.
Sorry for the late notice!

Thanks!

**Comment by oodu** [comment]
Data Privacy Statement is enabled local dataverse.no and local test.dataverse.no and is pointing to  [(https://site.uit.no/dataverseno/about/policy-framework/access-and-use-policy/):

curl -X PUT -d https://site.uit.no/dataverseno/about/policy-framework/access-and-use-policy/ http://localhost:8080/api/admin/settings/:ApplicationPrivacyPolicyUrl

**Comment by philippconzett** [comment]
Takk!
