### ISSUE TITLE
Geolocation cleaning before upgrading to v5.13

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#35]
After upgrading to v5.13, it turned out that several of the values in the metadata field value in table datasetfieldvalue are not in a compliant format. For example, some values use °, ', and '' instead of decimal format; some values use comma (,) instead of period (.).

To clean up these fields, we need to run the SQL script **_dvno_geolocation_cleaning_v5_13.sql** shared in channel General in Teams. Please run the script in test to check if everything works. Thanks!

**Comment by philippconzett** [comment]
I have updated the SQL script according to the feedback from Loïc in Teams. See new file "_dvno_geolocation_cleaning_v5_13_2023-02-24.sql" in Teams.

Short overview of changes:

VYWBAD:

Changed: set value=null (we don't know what coordinates the researcher had in mind; we'll fix this after cloud migration)

update datasetfieldvalue set value=null where id=17895;
update datasetfieldvalue set value=null where id=17896;
update datasetfieldvalue set value=null where id=17897;
update datasetfieldvalue set value=null where id=17898;
update datasetfieldvalue set value=null where id=21626;
update datasetfieldvalue set value=null where id=21636;
update datasetfieldvalue set value=null where id=21644;
update datasetfieldvalue set value=null where id=21651;


9QKUIQ:

No changes; use 77, we'll fix this after cloud migration.

update datasetfieldvalue set value='23.916667' where id=134095;
update datasetfieldvalue set value='31' where id=134106;
update datasetfieldvalue set value='69.75' where id=134118;
update datasetfieldvalue set value='77' where id=134120;


@4tikhonov @Louis-wr @oodu  Please let me know if there are still things we need to change. Thanks!

**Comment by Louis-wr** [comment]
https://github.com/DataverseNO/dataverse-docker/blob/dataverse.no/distros/dataverse.no/migration/_dvno_geolocation_cleaning_v5_13.sql

**Comment by philippconzett** [comment]
After login to local dataverse.no and test.dataverse.no is disabled, but before migration:
- [ ] Loïc: Create new list of invalid values.
- [ ] Philipp: Create new script to change invalid values to valid values.
- [ ] Loïc/Obi: Run the script
