### ISSUE TITLE
Handling Datasets that No Longer Comply With Licensing Rules as of v5.10

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/local.dataverse.no#9]
Before we upgrade to v5.10, we need to make sure that the license/Terms of Use information in existing datasets complies with the new licensing rules introduces as of v5.10. Dataverse has provided some SQL commands to find possible non-complying datasets (see [release notes](https://github.com/IQSS/dataverse/releases/tag/v5.10)).

@oodu or @Louis-wr 
Please run the queries below on the DataverseNO database (cripslock), and send me the results as plain text files by email. Thanks!

**Finding Datasets with a CC0 License and Non-Empty Terms:**
`select CONCAT('doi:', dvo.authority, '/', dvo.identifier), v.alias as dataverse_alias, case when versionstate='RELEASED' then concat(dv.versionnumber, '.', dv.minorversionnumber) else versionstate END  as version, dv.id as datasetversion_id, t.id as termsofuseandaccess_id, t.termsofuse, t.confidentialitydeclaration, t.specialpermissions, t.restrictions, t.citationrequirements, t.depositorrequirements, t.conditions, t.disclaimer from dvobject dvo, termsofuseandaccess t, datasetversion dv, dataverse v where dv.dataset_id=dvo.id and dv.termsofuseandaccess_id=t.id and dvo.owner_id=v.id and t.license='CC0' and not (t.termsofuse is null and t.confidentialitydeclaration is null and t.specialpermissions is null and t.restrictions is null and citationrequirements is null and t.depositorrequirements is null and t.conditions is null and t.disclaimer is null);`

**Finding and Modifying Datasets without a CC0 License and with Empty Terms:**
`select CONCAT('doi:', dvo.authority, '/', dvo.identifier), v.alias as dataverse_alias, case when versionstate='RELEASED' then concat(dv.versionnumber, '.', dv.minorversionnumber) else versionstate END  as version, dv.id as datasetversion_id, t.id as termsofuseandaccess_id, t.termsofuse, t.confidentialitydeclaration, t.specialpermissions, t.restrictions, t.citationrequirements, t.depositorrequirements, t.conditions, t.disclaimer from dvobject dvo, termsofuseandaccess t, datasetversion dv, dataverse v where dv.dataset_id=dvo.id and dv.termsofuseandaccess_id=t.id and dvo.owner_id=v.id and t.license='NONE' and t.termsofuse is null;`

**Comment by oodu** [comment]
[​txt icon] Finding_and_Modifying_Datasets_without_a_CC0_License_and_with_Empty_Terms.txt<https://universitetetitromso.sharepoint.com/:t:/r/sites/O365-UiT-DvNO-cloud-deployment/Shared%20Documents/General/Finding_and_Modifying_Datasets_without_a_CC0_License_and_with_Empty_Terms.txt?csf=1&web=1&e=83mmg1>

[​txt icon] Finding_Datasets_with_a_CC0_License_anNon-EmptyTerms.txt<https://universitetetitromso.sharepoint.com/:t:/r/sites/O365-UiT-DvNO-cloud-deployment/Shared%20Documents/General/Finding_Datasets_with_a_CC0_License_anNon-EmptyTerms.txt?csf=1&web=1&e=XLsmS2>

Hilsen Obi

**Comment by philippconzett** [comment]
Thanks! I'll get these datasets fixed by the responsible curators and will notice you once they are fixed.

**Comment by philippconzett** [comment]
Task list:
BEFORE we implement Multi Licenses Support:
- [ ] Create list of datasets where we need to change Terms of use (Philipp)
- [ ] Ask curators to carry out changes (Philipp)
AFTER we have implemented Multi Licenses Support:
- [ ] Change standard terms other than CC0 (e.g. CC BY) that are specified in _Terms of Use_ field, to the new predefined licenses.

**Comment by philippconzett** [comment]
Heads-up: We've got feedback from the affected partner institutions. UiT will decide on their datasets in a meeting next week, on Wednesday August 30.

**Comment by philippconzett** [comment]
We are now ready to do some clean up in the Terms of Use that won't be valid anymore once we have implement Multiple Standard Licenses Support.

@4tikhonov @Louis-wr @oodu 
In our Azure test environment, please run the file "_dvno_ToU_cleaning_v5_10.sql" in the folder General >> Licensing in Teams, and notice me once done. Thanks!

**Comment by philippconzett** [comment]
There are also one dataset where we need to move the content of one Terms of Use field to another, but the content is quite large (many rows), so I wonder whether we should use the command suggested by Dataverse:

> update termsofuseandaccess set termsofuse='New text.' where id=<id>;

or whether we should do this change using PHPmyAdmin or similar tool?

Any suggestions, @4tikhonov @Louis-wr @oodu ?

**Comment by Louis-wr** [comment]
[Finding_and_Modifying_Datasets_without_a_CC0_License_and_with_Empty_Terms.txt](https://github.com/DataverseNO/local.dataverse.no/files/10464395/Finding_and_Modifying_Datasets_without_a_CC0_License_and_with_Empty_Terms.txt)
[Finding_Datasets_with_a_CC0_License_anNon-EmptyTerms.txt](https://github.com/DataverseNO/local.dataverse.no/files/10464396/Finding_Datasets_with_a_CC0_License_anNon-EmptyTerms.txt)

**Comment by Louis-wr** [comment]
[_dvno_ToU_cleaning_v5_10.txt](https://github.com/DataverseNO/local.dataverse.no/files/10464421/_dvno_ToU_cleaning_v5_10.txt)

**Comment by oodu** [comment]
The clean up of the "Terms of Use" is done.

**Comment by philippconzett** [comment]
We need to run another clean-up round for invalid Terms of Use. In current production environment (dataverse.no), run the SQL queries in file "_dvno_ToU_cleaning_v5_10_round_2.sql" in DvNO Cloud Deployment teams >> General >> Licensing.

Plan:
1. The day after login is disabled, Philipp will create new SQL script.
2. Obi will run the script in local installation.

**Comment by philippconzett** [comment]
Fixed.
